- name: Проверка директорий и их создание, при отсутствии
  file:
      path: "{{ item }}"
      state: directory
      mode: '0755'
      owner: root
      group: root
  loop:
    - /opt/traefik/data
    - /opt/traefik/data/dynamic

- name: Деплой сатического конфига
  template:
    src: traefik.yml.j2
    dest: /opt/traefik/data/traefik.yml
    mode: '0644'
  notify: Перезапуск traefik

- name: Деплой динамического конфига
  template:
    src: global.yml.j2
    dest: /opt/traefik/data/dynamic/global.yml
    mode: '0644'
    
- name: Генерация docker-compose traefik
  template:
    src: docker-compose.yml.j2
    dest: /opt/traefik/docker-compose.yml

- name: Создание acme.json для traefik
  ansible.builtin.command:
    cmd: install -m 600 /dev/null /opt/traefik/data/acme.json
  args:
    creates: /opt/traefik/data/acme.json

- name: Деплой traefik
  community.docker.docker_compose_v2:
    project_src: /opt/traefik
    files:
      - docker-compose.yml
    state: present